import axios from "axios";
import { getToken } from "../services/Auth";

export const musicAPI = axios.create({
  baseURL: "https://api.spotify.com/v1/",
});

musicAPI.interceptors.request.use((config) => {
  config.headers["Authorization"] = `Bearer ${getToken()}`;
  return config;
});

musicAPI.interceptors.response.use(
  (ok) => ok,
  (e) => {
    if (!axios.isAxiosError(e)) throw Error("Unknown Error");

    if (!isSpotifyErrorResponse(e.response?.data)) throw Error("Unknown Error");

    throw Error(e.response?.data.error.message, { cause: e });
  }
);

// Generated by https://quicktype.io

export function isSpotifyErrorResponse(res: any): res is SpotifyErrorResponse {
  return res && "error" in res && "message" in res.error;
}

export interface SpotifyErrorResponse {
  error: {
    status: number;
    message: string;
  };
}
